config/routes.rb
Rails.application.routes.draw do
  get '/teachers' => 'teachers#index', as: :teacher_root # creates user_root_path
  get 'teachers/:id/miscursos' => 'teachers#my_courses', as: :my_courses
  get 'evaluation/:evaluation_id/students/:id/new' => 'students#add_student_to_evaluation', as: :new_evaluation_add_student
  get 'evaluation/:evaluation_id/students' => 'students#index_evaluation_students', :as => :index_evaluation_students
  get 'evaluations/:evaluation_id/students/calificate' => 'students#edit_evaluation_students', :as => :edit_evaluation_students
  patch 'evaluations/:evaluation_id/student/:student_id/update' => 'students#update_calification', :as => :update_evaluation_student
  devise_for :teachers

  resources :evaluations do
    resources :students, except: :create
  end

  resources :students
  resources :subjects

  resources :courses do
    resources :students
    resources :teachers
    resources :evaluations
  end

  resources :subjects do
    resources :courses
  end

  resources :teachers do
    resources :courses
  end




end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :course
  has_many :evaluation_students, dependent: :destroy
  has_many :students, through: :evaluation_students, dependent: :destroy

  validates :title, presence: true
  validates :min_score, presence: true, numericality: {:greater_than_or_equal_to => 0}
  validates :date, presence: true
  #Agregar un chequeo de fecha que corresponda segun el año de cursada.
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    #
    if params[:course_id].present?
      @evaluations = Course.find(params[:course_id]).evaluations
    else
      @evaluations = Evaluation.all
    end
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new

  end

  # GET /evaluations/1/edit
  def edit
    params[:course_id] = @evaluation.course_id
  end

  # POST /evaluations
  # POST /evaluations.json
  def create

    @evaluation = Evaluation.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Se ha creado correctamente' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        params[:course_id] = params[:evaluation][:course_id]
        format.html { render :new, :params => params[:course_id] }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.fetch(:evaluation, {})
      params.require(:evaluation).permit(:title, :date, :course_id, :min_score)
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper

  def evaluation_info(evaluation)
    evaluation.course.subject.name + ' ' + evaluation.title + ' ' + evaluation.date.to_s
  end

  def inscriptos(evaluation)
    evaluation.evaluation_students.count
  end

  def ausentes(evaluation)
    evaluation.evaluation_students.where(:score => 0).count.to_s
    #EvaluationStudent.where(:evaluation_id => evaluation.id, :score => 'Ausente').count
  end

  def aprobados(evaluation)
    evaluation.evaluation_students.where("score >= #{evaluation.min_score}").count.to_s
    #EvaluationStudent.where("evaluation_id = #{evaluation.id} and score >= #{evaluation.min_score} and score <> 'Ausente'").count.to_s
  end

  def desaprobados(evaluation)
    evaluation.evaluation_students.where("score BETWEEN 1 AND #{evaluation.min_score} ").count.to_s
    #EvaluationStudent.where("evaluation_id = #{evaluation.id} and score <= #{evaluation.min_score} and score <> 'Ausente'").count.to_s
  end

  def porcentaje_aprobados(evaluation)
    ((aprobados(evaluation).to_f/inscriptos(evaluation).to_f)*100).to_s
  end

end

app/views/evaluations/_form.html.erb
<%= simple_form_for(@evaluation) do |f| %>
  <%= f.error_notification %>

   <div class="form-inputs ">
    <%= f.input :title, required: true, label: "Titulo descriptivo"%>
    <%= f.input :date, required: true, label: "Fecha de examen", input_html: {placeholder: Time.now}%>
    <%= f.input :min_score, required: true, label: "Nota minima de aprobacion", input_html: {value: 4} %>
    <%= f.association :course, :as => :hidden, input_html: {value: params[:course_id]}%>
  </div>

  <div class="form-actions form-inline">
    <%= f.button :submit, "Agregar evaluacion", class: 'btn btn-success' %>
    <%= link_to 'Atras', evaluations_path, class: 'btn btn-danger' %>
  </div>


<% end %>

app/views/evaluations/edit.html.erb
<h1>Editar Evaluacion</h1>

<%= render 'form', evaluation: @evaluation %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th class="panel-heading">Titulo</th>
    <th>Fecha</th>
    <th>Puntaje de Aprobación</th>
    <th>Curso</th>
    <th colspan="5">Opciones</th>
  </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
  <tr>
    <td><%= evaluation.title %></td>
    <td><%= evaluation.date %></td>
    <td><%= evaluation.min_score %></td>
    <td><%= evaluation.course.subject.name %></td>
    <td><%= link_to 'Inscribir Alumnos', evaluation_students_path(evaluation) %></td>
    <td><%= link_to 'Ver inscriptos/Calificar', index_evaluation_students_path(evaluation)%></td>

    <td><%= link_to 'Editar', edit_evaluation_path(evaluation), class: 'glyphicon glyphicon-pencil'%></td>
    <td><%= link_to 'Eliminar!', evaluation, method: :delete, data: { confirm: '¿Estas seguro?' }, class: 'text text-danger glyphicon glyphicon-trash' %></td>
  </tr>
    <% end %>
  </tbody>
</table>

<div class="btn-group btn-group-sm">
  <%= link_to 'Volver', courses_path, class: 'btn btn-danger' %>
</div>

app/views/evaluations/new.html.erb
<h1>Agregar Evaluacion</h1>

<%= render 'form', evaluation: @evaluation %>

app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>
<p>Examen</p>
<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Titulo</th>
    <th>Fecha</th>
    <th>Puntaje de Aprobación</th>
    <th>Curso</th>
    <th colspan="5">Opciones</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @evaluation.title %></td>
    <td><%= @evaluation.date %></td>
    <td><%= @evaluation.min_score %></td>
    <td><%= @evaluation.course.subject.name %></td>
    <td><%= link_to 'Editar', edit_evaluation_path(@evaluation), class: 'glyphicon glyphicon-pencil'%></td>
    <td><%= link_to 'Eliminar!', @evaluation, method: :delete, data: { confirm: '¿Estas seguro?' }, class: 'text text-danger glyphicon glyphicon-trash' %></td>
  </tr>
  </tbody>
</table>

<div class="btn-group btn-group-sm">
  <%= link_to 'Volver', request.referrer, class: 'btn btn-danger' %>
</div>