config/routes.rb
Rails.application.routes.draw do
  get '/teachers' => 'teachers#index', as: :teacher_root # creates user_root_path
  get 'teachers/:id/miscursos' => 'teachers#my_courses', as: :my_courses
  get 'evaluation/:evaluation_id/students/:id/new' => 'students#add_student_to_evaluation', as: :new_evaluation_add_student
  get 'evaluation/:evaluation_id/students' => 'students#index_evaluation_students', :as => :index_evaluation_students
  get 'evaluations/:evaluation_id/students/calificate' => 'students#edit_evaluation_students', :as => :edit_evaluation_students
  patch 'evaluations/:evaluation_id/student/:student_id/update' => 'students#update_calification', :as => :update_evaluation_student
  devise_for :teachers

  resources :evaluations do
    resources :students, except: :create
  end

  resources :students
  resources :subjects

  resources :courses do
    resources :students
    resources :teachers
    resources :evaluations
  end

  resources :subjects do
    resources :courses
  end

  resources :teachers do
    resources :courses
  end




end

app/models/student.rb
class Student < ApplicationRecord
  has_many :course_students, dependent: :destroy
  has_many :courses, through: :course_students
  has_many :evaluation_students, dependent: :destroy
  has_many :evaluations, through: :evaluation_students

  accepts_nested_attributes_for :evaluation_students
  accepts_nested_attributes_for :course_students




 accepts_nested_attributes_for :courses

 before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true
  validates :surname, presence: true
  validates :dni, presence: true, uniqueness: true, length: {minimum: 6, maximum: 10}
  validates :email, presence: true, format: {:with => VALID_EMAIL_REGEX,
                                            :message => 'El mail debe ser del tipo "ejemplo1234@abc.com"'},
                                         uniqueness: {case_sensitive: false}
  validates :legajo, presence: true, uniqueness: true
  validates_associated :courses





end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [ :add_student_to_evaluation, :show, :edit, :update, :destroy]
  before_action :set_evaluation_student, only: [:update_calification]
  before_action :set_course, except: [:add_student_to_evaluation]
  # GET /students
  # GET /students.json
  def index
    if params[:evaluation_id].present?
      @evaluation = Evaluation.find(params[:evaluation_id])
      @course = @evaluation.course
    end
    @students = @course.students.order(:surname, :name)
  end

  # GET /stu
  # dents/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
      @student = Student.new
      @course.students.build
  end


  def add_student_to_evaluation
    if params[:evaluation_id].present?
      @evaluation = Evaluation.find(params[:evaluation_id])
      @evaluation.students << @student
      respond_to do |format|
        if @evaluation.save
          format.html { redirect_to evaluation_path(@evaluation), notice: 'Se ha inscripto correctamente.' }
          #format.json { render :show, status: :created, location: @student }
        else
          format.html { render :new }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def index_evaluation_students
    @evaluation = Evaluation.find(params[:evaluation_id])
    @students = @evaluation.students

    render 'students/enrolled'
  end

  def edit_evaluation_students
    @evaluation = Evaluation.find(params[:evaluation_id])
    @students = @evaluation.students

    render 'students/calificate'
  end

  def update_calification
    score = params[:student][:evaluation_student][:score]
    comment = params[:student][:evaluation_student][:comment]
    @evaluation_student.update(:score => score, :comment => comment )
    respond_to do |format|
      if @evaluation_student.save
        format.html { redirect_to request.referrer, notice: 'Parametros actualizados.' }
        format.json { render :show, status: :ok, location: @student }
      end
    end
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = @course.students.new(student_params)

    respond_to do |format|
      if @course.save
    #    Course.find(params[:course_id]).students << @student
        format.html { redirect_to course_students_path(@course), notice: 'Estudiante creado' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to course_students_path(@course), notice: 'Parametros de estudiantes actualizados.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Estudiante eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_course
      if(params[:course_id].present?)
        @course=Course.find(params[:course_id])
      end
    end

    def set_evaluation_student

      @evaluation_student = EvaluationStudent.find_by(:evaluation_id => params[:evaluation_id], :student_id => params[:student_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.fetch(:student, {})
      params.require(:student).permit(:name, :surname, :dni, :legajo, :email, :course_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper

  def not_inscripted(evaluation_id, student_id)
    EvaluationStudent.where(evaluation_id: evaluation_id, student_id: student_id).empty?
  end

  def evaluacion(evaluation, student)
    EvaluationStudent.where(:evaluation_id => evaluation.id, student_id: student.id).first
  end

end

app/views/students/_form.html.erb
<%= simple_form_for([@course, student], html: {class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Nombre', class: 'form-group form-control' %>
    <%= f.input :surname, label: 'Apellido', class: 'form-group' %>
    <%= f.input :dni, label: 'DNI', class: 'form-group' %>
    <%= f.input :email, placeholder: 'mail@mail.com', class: 'form-group'%>
    <%= f.input :legajo, class: 'form-group' %>

  </div>

  <div class="form-actions form-inline">
    <%= f.submit 'Aceptar', class: 'btn btn-info' %>

  </div>
<% end %>

app/views/students/_form_evaluate.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes Inscriptos</h1>

<h3>Examen <%= evaluation_info(@evaluation) %></h3>

<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Legajo</th>
    <th>Dni</th>
    <th>Estado</th>
    <th>Nota</th>
    <th>Comentarios</th>
    <th colspan="5">Opciones</th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.surname %></td>
      <td><%= student.legajo %></td>
      <td><%= student.dni %></td>


      <td><% if evaluacion(@evaluation, student).status.blank? %>
          <%= "Por calificar" %>
          <% else %>
        <%= evaluacion(@evaluation, student).status %></td>
        <% end %>

      <%= simple_form_for student, url: update_evaluation_student_path(:student_id => student.id) ,:html => { :class => 'form-horizontal' } do |f| %>
        <%= f.error_notification %>

        <%= f.simple_fields_for evaluacion(@evaluation, student)  do |es| %>
          <td><%= es.input :score, hint: "Puntaje de 0 a 10. 0(cero) == Ausente", label: false %></td>
          <td><%= es.input :comment, as: :text, hint: "Cualquier comentario que quiera agregarse", label: false %></td>
          <%#= f.input :course_ids, :as => :hidden, class: 'form-group', :input_html => { disabled:true, :value => params[:course_id]} %>


        <% end %>
        <td class="form-actions form-inline">
          <%= f.submit 'Calificar', class: 'btn btn-warning' %>
        </td>



    <% end %>
  <%end%>

    </tr>
  </tbody>

</table>

<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Fecha de evaluacion</th>
    <th>Alumnos Inscriptos</th>
    <th>Alumnos Aprobados/Porcentaje</th>
    <th>Alumnos Desaprobados</th>
    <th>Alumnos Ausentes</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @evaluation.date %></td>
    <td><%= inscriptos(@evaluation) %></td>
    <td><%= aprobados(@evaluation) + "/" +  porcentaje_aprobados(@evaluation) +'%' %></td>
    <td><%= desaprobados(@evaluation) %></td>
    <td><%= ausentes(@evaluation) %></td>
  </tr>
  </tbody>
</table>






<div class="btn-group btn-group-sm">
  <%= link_to 'Volver', course_evaluations_path(@evaluation.course), class: 'btn btn-danger' %>
</div>

app/views/students/calificate.html.erb
<h1>Calificar Estudiantes</h1>

<%= render 'form_evaluate', students: @students, evaluation: @evaluation %>

app/views/students/edit.html.erb
<h1>Editar estudiante</h1>

<%= render 'form', student: @student %>

app/views/students/enrolled.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes Inscriptos</h1>

<h3>Examen <%= evaluation_info(@evaluation) %></h3>

<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Legajo</th>
    <th>Dni</th>
    <th>Nota</th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.surname %></td>
      <td><%= student.legajo %></td>
      <td><%= student.dni %></td>
      <td><%= student.evaluation_students.first.score %></td>

    </tr>
  <% end %>
  </tbody>
</table>



<div class="btn-group btn-group-sm">
  <%= link_to 'Calificar a todos', edit_evaluation_students_path(@evaluation), class: 'btn btn-info'%>
  <%= link_to 'Volver', request.referrer, class: 'btn btn-danger' %>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Legajo</th>
    <th colspan="5">Opciones</th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.surname %></td>
      <td><%= student.legajo %></td>
      <% if params[:evaluation_id].present? && not_inscripted(@evaluation.id, student.id) %>
        <td><%= link_to 'Inscribir', new_evaluation_add_student_path(params[:evaluation_id], student), class: 'glyphicon glyphicon-plus' %></td>
      <% else %>
        <td><%= link_to 'Mostrar', course_student_path(@course, student), class: 'glyphicon glyphicon-zoom-in' %></td>
      <% end %>
      <td><%= link_to 'Editar', edit_course_student_path(@course, student), class: 'glyphicon glyphicon-pencil'%></td>
      <td><%= link_to 'Eliminar!', student, method: :delete, data: { confirm: '¿Estas seguro?' }, class: 'text text-danger glyphicon glyphicon-trash' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="btn-group btn-group-sm">
  <%= link_to 'Nuevo Estudiante', new_course_student_path(@course), class: 'btn btn-info' %>
  <%= link_to 'Volver', courses_path, class: 'btn btn-danger' %>
</div>

app/views/students/new.html.erb
<% if params[:course_id].present? %>
  <h1>Agregar Nuevo Estudiante a <%= course_name_by_id(params[:course_id])%></h1>
<% else %>
  <h1>Agregar Nuevo Estudiante</h1>
<% end %>

<%= render 'form', student: @student %>

<%= link_to 'Atrás', request.referrer, class: 'btn btn-danger' %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Mail</th>
    <th>Legajo</th>
    <th>Dni</th>
    <th colspan="5">Opciones</th>
  </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @student.name %></td>
      <td><%= @student.surname %></td>
      <td><%= @student.email %></td>
      <td><%= @student.legajo %></td>
      <td><%= @student.dni %></td>
      <td><%= link_to 'Editar', edit_course_student_path(@course, @student), class: 'glyphicon glyphicon-pencil'%></td>
      <td><%= link_to 'Eliminar!', @student, method: :delete, data: { confirm: '¿Estas seguro?' }, class: 'text text-danger glyphicon glyphicon-trash' %></td>
    </tr>
  </tbody>
</table>

<div class="btn-group btn-group-sm">
  <%= link_to 'Volver', students_path, class: 'btn btn-danger' %>
</div>