config/routes.rb
Rails.application.routes.draw do
  get '/teachers' => 'teachers#index', as: :teacher_root # creates user_root_path
  get 'teachers/:id/miscursos' => 'teachers#my_courses', as: :my_courses
  get 'evaluation/:evaluation_id/students/:id/new' => 'students#add_student_to_evaluation', as: :new_evaluation_add_student
  get 'evaluation/:evaluation_id/students' => 'students#index_evaluation_students', :as => :index_evaluation_students
  get 'evaluations/:evaluation_id/students/calificate' => 'students#edit_evaluation_students', :as => :edit_evaluation_students
  patch 'evaluations/:evaluation_id/student/:student_id/update' => 'students#update_calification', :as => :update_evaluation_student
  devise_for :teachers

  resources :evaluations do
    resources :students, except: :create
  end

  resources :students
  resources :subjects

  resources :courses do
    resources :students
    resources :teachers
    resources :evaluations
  end

  resources :subjects do
    resources :courses
  end

  resources :teachers do
    resources :courses
  end




end

app/models/teacher.rb
class Teacher < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :courses
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true
  validates :surname, presence: true
  validates :email, presence: true, uniqueness: true,
            format: { with: VALID_EMAIL_REGEX, :message => "Debe ser del tipo 'nombre@host.com'"}
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy, :my_courses]

  # GET /teachers
  # GET /teachers.json
  def index
    if params[:course_id].present?
      @teachers = Course.find(params[:course_id]).teachers
    else
      @teachers = Teacher.all
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Profesor agregado correctamente' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_courses
    @misCursos
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
      @misCursos = @teacher.courses
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.fetch(:teacher, {}).permit{:username}
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper

  def teacher_courses_string
    cursos = ""
    @teacher.courses.each do |c|

      cursos << c.subject.name + ', ' + c.year.to_s + ";\n"

    end
    cursos
  end


end

app/views/teachers/_form.html.erb
<%= simple_form_for(@teacher) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%=  edit_teacher_registration_path(@teacher) %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<% content_for :page_title, 'Profesores'%>
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Docentes</h1>
  <h3>Bienvenido <%= current_teacher.name %> <%= current_teacher.surname %></h3>
  <table class="table table-hover table-bordered">
    <thead >
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Mail</th>
      <th colspan="3">Opciones</th>
    </tr>
    </thead>

    <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.surname %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Mostrar Informacion', teacher %></td>
        <td>
          <%= link_to 'Editar Informacion', edit_teacher_registration_path(teacher) %></td>
        <td><%= link_to 'Cursos Asignados', my_courses_path(teacher) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<br>
<div class="btn-group btn-group-sm">
  <%#= link_to 'Nuevo Docente', new_teacher_registration_path, class: 'btn btn-info' %>
</div>
</div>

app/views/teachers/my_courses.html.erb
<%= content_for :page_title, "Mis Cursos"%>
<p id="notice"><%= notice %></p>

<table class="table table-hover table-bordered">
  <caption>Mis Cursos</caption>
  <thead >
  <tr>
    <th>Nombre</th>
    <th>Año</th>
    <th>Fecha asignacion</th>
  </tr>
  </thead>

  <tbody>
  <% @misCursos.each do |c| %>
  <tr>
    <td><%= link_to c.subject.name, course_path(c) %></td>
    <td><%= c.year %></td>
    <td><%= c.created_at.strftime('%b %m %Y') %></td>
      <% end %>
  </tr>
  </tbody>
</table>
<div class="btn-group btn-group-sm">
    <%= link_to 'Atrás', teachers_path, class: 'btn btn-danger' %>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Atrás', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover table-bordered">
  <thead >
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Mail</th>
    <th>Nombre Usuario</th>
    <th><%= link_to "Mis cursos", my_courses_path(@teacher) %></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @teacher.name %></td>
    <td><%= @teacher.surname %></td>
    <td><%= @teacher.email %></td>
    <td><%= @teacher.username %></td>
    <td><%= teacher_courses_string %> <%#-helper-%>

    </td>


  </tr>
  </tbody>
</table>
<div class="btn-group btn-group-sm">
<%#= link_to 'Editar Informacion', edit_subject_path(@teacher), class: 'btn btn-info' %>
<%= link_to 'Atrás', teachers_path, class: 'btn btn-danger' %>
</div>