config/routes.rb
Rails.application.routes.draw do
  get '/teachers' => 'teachers#index', as: :teacher_root # creates user_root_path
  get 'teachers/:id/miscursos' => 'teachers#my_courses', as: :my_courses
  get 'evaluation/:evaluation_id/students/:id/new' => 'students#add_student_to_evaluation', as: :new_evaluation_add_student
  get 'evaluation/:evaluation_id/students' => 'students#index_evaluation_students', :as => :index_evaluation_students
  get 'evaluations/:evaluation_id/students/calificate' => 'students#edit_evaluation_students', :as => :edit_evaluation_students
  patch 'evaluations/:evaluation_id/student/:student_id/update' => 'students#update_calification', :as => :update_evaluation_student
  devise_for :teachers

  resources :evaluations do
    resources :students, except: :create
  end

  resources :students
  resources :subjects

  resources :courses do
    resources :students
    resources :teachers
    resources :evaluations
  end

  resources :subjects do
    resources :courses
  end

  resources :teachers do
    resources :courses
  end




end

app/views/layouts/_footer.html.erb
<div>Footer</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= image_tag 'vaskon.jpg', class: "menu_icon", size: '50x50'%></li>
                <li><%= image_tag 'sicilia.png', class: "menu_icon", size: '50x50'%></li>
                <li class="h3 navbar-text text-center"> Sistema de nada</li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Inicio", page_path('home') %></li>
                <li><%= link_to "Acerca de", page_path('about')%></li>
                <% if teacher_signed_in? %>


                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_teacher.name %>
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-header">Opciones</li>
                    <li><%= link_to("Mi perfil", teacher_path(current_teacher)) %></li>
                    <li><%= link_to("Ver Materias", subjects_path)%></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to('Cerrar Sesion', destroy_teacher_session_path, method: :delete) %>
                    </li>
                  </ul>
                </li>


                <% else %>
                <li >

                    <%= link_to('Registrarse', new_teacher_registration_path)  %>
                </li>
                <li >
                    <%= link_to('Iniciar Sesion', new_teacher_session_path)  %>
                </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <br><br><br><br>

  <div class="container">
    <%= yield %>
    <%= console %>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </div>




  </body>


</html>